ASoC: img: Fix compilation issue caused when selecting EVENT_TIMER_LOCAL
When event timer local is selected it causes below compilation failures.

[..]

sound/soc/img/pistachio-event-timer-local.c: In function ‘pistachio_evt_get_time_cyc’:
sound/soc/img/pistachio-event-timer-local.c:55:2: error: implicit declaration of function ‘_pistachio_evt_read_ns’ [-Werror=implicit-function-declaration]
  ret = _pistachio_evt_read_ns(evt, cyc);
  ^
sound/soc/img/pistachio-event-timer-local.c: In function ‘pistachio_evt_clk_notifier_cb’:
sound/soc/img/pistachio-event-timer-local.c:143:3: error: implicit declaration of function ‘pistachio_evt_read_ns’ [-Werror=implicit-function-declaration]
   pistachio_evt_read_ns(evt, NULL);
   ^
sound/soc/img/pistachio-event-timer-local.c:147:3: error: implicit declaration of function ‘pistachio_evt_clk_rate_change’ [-Werror=implicit-function-declaration]
   pistachio_evt_clk_rate_change(evt);

[..]

Fix the compilation issue by using the right api's
as available part of event timer local.

Issue ID: 74511

Change-Id: Id03fc41283a303815632a140fb2ba1fd282f8a63
Signed-off-by: Govindraj Raja <Govindraj.Raja@imgtec.com>